# -*- coding: utf-8 -*-
"""Dashboard_proyek

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ae1U1MYqyfvzRqyNj67uNqvBAg0GDwE6
"""

# pip install streamlit

# Import necessary libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import streamlit as st

# Load Data
@st.cache_data
def load_data():
    day_df = pd.read_csv("https://raw.githubusercontent.com/EsterTriW/Proyek-Analisis-Data/main/day.csv")
    hour_df = pd.read_csv("https://raw.githubusercontent.com/EsterTriW/Proyek-Analisis-Data/main/hour.csv")
    return day_df, hour_df

day_df, hour_df = load_data()

st.title("Dashboard Analisis Penyewaan Sepeda")

# Data Wrangling and Preparation
day_df['dteday'] = pd.to_datetime(day_df['dteday'])

# Exploratory Data Analysis (EDA)
st.subheader("Tren Penyewaan Sepeda 2011-2012")

# Plotting Tren Penyewaan Sepeda
fig, ax = plt.subplots(figsize=(10, 5))
sns.lineplot(data=day_df, x="dteday", y="cnt", hue="yr", palette="tab10", ax=ax)
ax.set_title("Tren Penyewaan Sepeda 2011-2012")
ax.set_xlabel("Tanggal")
ax.set_ylabel("Jumlah Penyewaan")
plt.xticks(rotation=45)
st.pyplot(fig)

# Total Penyewaan Sepeda per Bulan
st.subheader("Total Penyewaan Sepeda per Bulan")
month = day_df.groupby(by="mnth").cnt.sum().reset_index()
fig, ax = plt.subplots(figsize=(10, 5))
sns.barplot(data=month, x="mnth", y="cnt", palette="coolwarm", ax=ax)
ax.set_xticklabels(["Jan", "Feb", "Mar", "Apr", "Mei", "Jun", "Jul", "Agu", "Sep", "Okt", "Nov", "Des"])
ax.set_title("Total Penyewaan Sepeda per Bulan")
ax.set_xlabel("Bulan")
ax.set_ylabel("Jumlah Penyewaan")
st.pyplot(fig)

# Total Penyewaan Sepeda per Musim
st.subheader("Total Penyewaan Sepeda per Musim")
musim = day_df.groupby(by="season")["cnt"].sum().reset_index()
musim["season"] = musim["season"].map({1: "Spring", 2: "Summer", 3: "Fall", 4: "Winter"})
fig, ax = plt.subplots(figsize=(10, 5))
sns.barplot(data=musim, x="season", y="cnt", palette="coolwarm", ax=ax)
ax.set_xticklabels(["Spring", "Summer", "Fall", "Winter"])
ax.set_title("Total Penyewaan Sepeda per Musim")
ax.set_xlabel("Musim")
ax.set_ylabel("Jumlah Penyewaan")
st.pyplot(fig)

# Rata-rata Penyewaan per Hari dalam Seminggu
st.subheader("Rata-rata Penyewaan Sepeda per Hari dalam Seminggu")
weekday_avg = day_df.groupby(by="weekday")["cnt"].mean().reset_index()
fig, ax = plt.subplots(figsize=(10, 5))
sns.barplot(data=weekday_avg, x="weekday", y="cnt", palette="coolwarm", ax=ax)
ax.set_title("Rata-rata Penyewaan Sepeda per Hari dalam Seminggu")
ax.set_xlabel("Hari")
ax.set_ylabel("Rata-rata Penyewaan")
st.pyplot(fig)

# Penyewaan Sepeda Berdasarkan Jam
st.subheader("Pola Penyewaan Sepeda Berdasarkan Jam")
jam = hour_df.groupby("hr")["cnt"].mean().reset_index()
fig, ax = plt.subplots(figsize=(10, 5))
sns.lineplot(data=jam, x="hr", y="cnt", marker="o", color="crimson", ax=ax)
ax.set_title("Pola Penyewaan Sepeda Berdasarkan Jam")
ax.set_xlabel("Jam")
ax.set_ylabel("Jumlah Penyewaan")
st.pyplot(fig)

# Pengaruh Cuaca terhadap Penyewaan Sepeda
st.subheader("Pengaruh Cuaca terhadap Penyewaan Sepeda")
fig, ax = plt.subplots(figsize=(10, 5))
sns.boxplot(data=day_df, x="weathersit", y="cnt", palette="coolwarm", ax=ax)
ax.set_xticklabels(["Mendung/berawan", "Cerah", "Hujan Ringan", "Hujan Lebat"])
ax.set_title("Pengaruh Cuaca terhadap Penyewaan Sepeda")
ax.set_xlabel("Kondisi Cuaca")
ax.set_ylabel("Jumlah Penyewaan")
st.pyplot(fig)

# Pengaruh Temperatur, Kelembaban, dan Kecepatan Angin
st.subheader("Pengaruh Faktor Lingkungan terhadap Penyewaan Sepeda")
fig, axes = plt.subplots(1, 3, figsize=(18, 6))

# 1. Suhu vs Jumlah Penyewaan
sns.scatterplot(data=day_df, x="temp", y="cnt", alpha=0.5, color="blue", ax=axes[0])
axes[0].set_title("Suhu vs Penyewaan Sepeda")
axes[0].set_xlabel("Suhu")
axes[0].set_ylabel("Jumlah Penyewaan")

# 2. Kelembaban vs Jumlah Penyewaan
sns.scatterplot(data=day_df, x="hum", y="cnt", alpha=0.5, color="green", ax=axes[1])
axes[1].set_title("Kelembaban vs Penyewaan Sepeda")
axes[1].set_xlabel("Kelembaban")

# 3. Kecepatan Angin vs Jumlah Penyewaan
sns.scatterplot(data=day_df, x="windspeed", y="cnt", alpha=0.5, color="red", ax=axes[2])
axes[2].set_title("Kecepatan Angin vs Penyewaan Sepeda")
axes[2].set_xlabel("Kecepatan Angin")

plt.tight_layout()
st.pyplot(fig)

# Penyewaan sepeda berdasarkan hari kerja dan hari libur
st.subheader("Total Penyewaan Sepeda berdasarkan hari kerja dan hari libur")
yearly_workday = day_df.groupby(by=["yr", "workingday"]).agg({
    "cnt": "sum"
}).reset_index()

yearly_workday["yr"] = yearly_workday["yr"].map({0: "2011", 1: "2012"})
yearly_workday["workingday"] = yearly_workday["workingday"].map({0: "Hari Libur", 1: "Hari Kerja"})

fig, ax = plt.subplots(figsize=(10, 5))
sns.barplot(data=yearly_workday, x="yr", y="cnt", hue="workingday", palette=["lightcoral", "royalblue"], ax=ax)
ax.set_title("Total Penyewaan Sepeda berdasarkan hari kerja dan hari libur")
ax.set_xlabel("Tahun")
ax.set_ylabel("Jumlah Penyewaan")
st.pyplot(fig)

# Penyewaan sepeda berdasarkan pengguna casual dan registered
st.subheader("Total Penyewaan Sepeda berdasarkan pengguna casual dan registered")
workday_summary = day_df.groupby(by= "workingday").agg({
    "casual": "sum",
    "registered":"sum"
}).reset_index()

workday_summary["workingday"] = workday_summary["workingday"].map({0: "Hari Libur", 1: "Hari Kerja"})
workday_summary = workday_summary.melt(id_vars="workingday", var_name="User Type", value_name="Count")

fig, ax = plt.subplots(figsize=(10, 5))
sns.barplot(data=workday_summary, x="workingday", y="Count", hue="User Type", palette=["lightblue", "salmon"], ax=ax)
ax.set_title("Total Penyewaan Sepeda berdasarkan pengguna casual dan registered")
ax.set_xlabel("Hari")
ax.set_ylabel("Jumlah Penyewaan")
st.pyplot(fig)